"""added_holidays

Revision ID: 7ab555b8a07a
Revises: 53c6eb5b4ff8
Create Date: 2021-01-28 03:13:03.947565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab555b8a07a'
down_revision = '53c6eb5b4ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holiday',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holiday')
    # ### end Alembic commands ###
