"""Initial_db

Revision ID: f235cdc69c7e
Revises: 
Create Date: 2020-11-22 15:10:36.772495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f235cdc69c7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('province', sa.Integer(), nullable=False),
    sa.Column('town', sa.Integer(), nullable=False),
    sa.Column('station', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('magnitude', sa.Integer(), nullable=True),
    sa.Column('method', sa.Integer(), nullable=True),
    sa.Column('analysis_period', sa.Integer(), nullable=True),
    sa.Column('data', sa.Integer(), nullable=True),
    sa.Column('validation_code', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('province', 'town', 'station', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement')
    # ### end Alembic commands ###
